### ISSUE TITLE
CPU hashrate drops

### ISSUE THREAD

**Issue by lvn2007** [nicehash/NiceHashQuickMiner#3]
For some reason, whenever I log out of remote desktop session (Anydesk), my CPU hashrate drops from 6.6 kH/s to 0.4 kH/s
Tried using XMRig from NiceHash miner and it works fine without any issue.

**Comment by nicehashdev** [comment]
That might be an issue that was fixed in one of later versions of XMRig. Can you try that on your own? QuickMiner still uses older version of XMRig.

**Comment by lvn2007** [comment]
Running latest version of XMRig works fine.
Running XMRig via QuickMiner caused problem as mentioned above.

**Comment by lvn2007** [comment]
I fixed this by simply replacing XMRig in QuickMiner with the latest version XMRig

**Comment by lvn2007** [comment]
Could you guys please update XMRig in NHQM with the latest version of XMRig? It's still showing on my end XMRig is still on 6.7.0

**Comment by nicehashdev** [comment]
This is on todo list and will be done in the near future once.

**Comment by gysnst2** [comment]
excavator also need to be updated in quickminer. i notice a 3-5 mh prop between the 2 versions

**Comment by lvn2007** [comment]
Can you guys update the latest XMRig to NHQM? I can't mine with CPU if using NHQM -- Which ultimately stop me from using NHQM

**Comment by nicehashdev** [comment]
We are aware of this, but currently this is low priority task. Updating XMRig in Excavator is not just recompilation but also merging of repos, signing and packing which takes quite some time. I am sorry about that, but there are other more important matters still to deal with.

**Comment by ironpossum** [comment]
Poking this as two months have gone by from the initial request. I appreciate that there are other priorities and I don't want this to get lost / forgotten. This seems like an easy win, even if it requires a bit of time to do. If we had the ability to simply replace the xmrig version ourselves as a workaround, then this wouldn't be so bad. As a side note, I believe the reason the hash rates are lower with this older version (6.7.0) is because it's not leveraging all the logical cores and only using physical cores (per my observation). Please and thank you =)

**Comment by lvn2007** [comment]
@ironpossum I hope they update XMRig soon. It's the only thing stopping me from using NHQM ...

**Comment by ironpossum** [comment]
Looks like I might have had a different issue than @lvn2007 has, my issue was that my hashrate was down as compared to the NH Miner, and my CPU utilization was only 50%. I was able to fix this by editing the nmqm.conf file and changing --cpu-max-threads-hint from 50 to 100 (this serves as a percentage of cores/threads to use). I guess my issue was not tied to the xmrig version. Sorry @lvn2007 =(

**Comment by kivechang** [comment]
I have the same problem, what time can  update XMRig?

**Comment by ardoslav** [comment]
I  have the same issues even after replacement of the latest version of the xmrig

**Comment by ardoslav** [comment]
hashrate is droping  after the pc is left alone cpu shows 100 utilization but the the temperature is 55 and after stop  and start of xmrig  the mining it is back to high temperature - in my case 75 degree, and real CPU utilization

**Comment by Dohtar1337** [comment]
Does the issue persist? @ardoslav @ironpossum @lvn2007
