### ISSUE TITLE
[FEATURE] Bring back the option to hide the excavator console

### ISSUE THREAD

**Issue by smrky1** [nicehash/NiceHashQuickMiner#697]
Please bring back the option to hide the excavator console window (I understand it has been removed in v0.5.3.0 RC).

I think it has been removed to prevent people from running NiceHash silently in background, but there are folks who prefer as little items on Windows Taskbar as possible (like me).

Maybe only as an option to manually add ""bHideMiningConsole" : true" to the config.

Thank you!

(btw. I know I can move the console window to another Desktop, but I would prefer to not have to do it manually)

**Comment by saxobroko** [comment]
An alternative to that suggestion could be requiring a UAC prompt to change settings in a gui and have the config file encrypted or something

**Comment by Riccorbypro** [comment]
+1 to this request. Just updated to 0.5.3.0 and I can no longer hide Excavator. The entire reason I like NHQM is the fact that I can just use the little tray icon to control it and forget about it while I do other things - having an icon in the task bar means Excavator is now sitting alongside all my actually-intended-to-be-used icons, and just adds another thing to skip over with Alt-Tab.

**Comment by MrDirtt** [comment]
Please bring this option back.  I use this miner on my main personal machine, mining all day long while working.  There is no need to display this window.

**Comment by Killua-Zolldyck** [comment]
Without this feature I will have to stop use QuickMiner.,, Why has this been removed? Not everyone is mining on a rig, where nobody cares of an open window.

**Comment by KingNewbs** [comment]
Not a fan of this change either. I think I can guess why you've removed it, but an explanation would be helpful, along with a way to reinstate the hidden excavator window option with whatever hoops you'd need us to jump through to be sure QM isn't being abused, if necessary.

**Comment by limacohen** [comment]
For now, using AHK:
```
IfWinExist, ahk_exe excavator.exe
  WinHide
```

**Comment by KingNewbs** [comment]
> For now, using AHK:
> 
> ```
> IfWinExist, ahk_exe excavator.exe
>   WinHide
> ```

Thanks. I don't usually keep AutoHotKey running, so switching back to the stable version works for me, for now. But I'll definitely save this workaround for the future.

**Comment by KingNewbs** [comment]
So, if we can't have the auto hide feature, I think a reasonable compromise would be adding a "minimize to the system tray" option, along with a "start minimized" option, to basically accomplish the same thing without actually "hiding" the window.

**Comment by limacohen** [comment]
I don't get why we would have to compromise here. If the issue is that you want the user (us) to be aware that the miner is running, then the excavator console is not the answer since it can be hidden with a [super simple (and possibly invisible) script](https://github.com/nicehash/NiceHashQuickMiner/issues/697#issuecomment-978562409). BUT, the tray icon _CAN'T_ be hidden by an external script/program. So, the problem was already solved to begin with… no need for this inconvenient half-measure.

**Comment by MrMrE** [comment]
- [x] #697]
# **D.I.Y**!

### **`"bHideMiningConsole" : true,`**
found in file 
##### **nhqm.conf**

i also change these for no reason i think
`	"bNoEULADialog" : true,`
`	"bNoMainDialog" : true,`
`	"bNoOptionsDialog" : true,`

**Comment by limacohen** [comment]
> # **D.I.Y**!
> ### **`"bHideMiningConsole" : true,`**
> found in file
> 
> ##### **nhqm.conf**

What do you mean @MrMrE? The whole point of this issue is the fact that `bHideMiningConsole` is not working anymore…

**Comment by MrMrE** [comment]
> > # **D.I.Y**!
> > ### **`"bHideMiningConsole" : true,`**
> > found in file
> > ##### **nhqm.conf**
> 
> What do you mean @MrMrE? The whole point of this issue is the fact that `bHideMiningConsole` is not working anymore…

oh sorry, still works for me on latest update for nicehash quick miner and im on latest updated win10 v.20H2 x64

**Comment by KingNewbs** [comment]
> > > # **D.I.Y**!
> > > ### **`"bHideMiningConsole" : true,`**
> > > found in file
> > > ##### **nhqm.conf**
> > 
> > 
> > What do you mean @MrMrE? The whole point of this issue is the fact that `bHideMiningConsole` is not working anymore…
> 
> oh sorry, still works for me on latest update for nicehash quick miner and im on latest updated win10 v.20H2 x64
> 
> i suggest maybe some repo installs like vb and java might also be causing it. good luck

Sounds like you're using the stable version (Stable release v0.5.2.0), which is still the same as the previous release candidate from May and retains the bHideMiningConsole functionality. The current RC ([Prerelease v0.5.3.0 RC](https://github.com/nicehash/NiceHashQuickMiner/releases/tag/v0.5.3.0_RC)) has this function intentionally removed, which is what we're discussing: 
`Removed hidden miner execution settings.`

**Comment by Hukuma1** [comment]
Imagine coming back to developing this thing after a 6-month hiatus and removing one of the most useful features. Come on... :/

**Comment by T0m0rr0w** [comment]
> Imagine coming back to developing this thing after a 6-month hiatus and removing one of the most useful features. Come on... :/

Tell me about it. Initially i thought i was doing something wrong until i came here to check issues. I rather prefer that the console window can be hidden but the tray icon cannot be hidden. That would be a nice compromise.

**Comment by harr2969** [comment]
It seems like they were pressured into this change by AV vendors. Maybe it was Norton, since they ended up putting a miner in their actual security product. At any rate, don't bow to pressure, this is an important feature for your real users.

**Comment by Draghmar** [comment]
This is really annoying. I don't like having additional windows open, regardless of PC I'm using at the moment.

**Comment by kkhalme** [comment]
What a PITA this policy is. I like NH generally, but not their condescending view on how their customers should use their mining machines. There's nothing sinister about being able to hide unnecessary windows if you use the same computer, owned by you, electricity paid by you, for other things at the same time. Companies and other parties who forbid miners can very easily block the applications in their security suite anyway. This is a convenience feature purely and should absolutely continue to exist in NH miners.

**Comment by darkmanlv** [comment]
Need to have this feature back. Will hide it anyway, but better that bHideMiningConsole works again if we need it.

**Comment by Draghmar** [comment]
> Need to have this feature back. Will hide it anyway, but better that bHideMiningConsole works again if we need it.
How will you hide it without this option? I tried AHK but for some reason it doesn't work for me.

**Comment by DonCaliOni** [comment]
> Need to have this feature back. Will hide it anyway, but better that bHideMiningConsole works again if we need it.

May I ask how you're hiding it? Thanks

**Comment by Draghmar** [comment]
Downgraded to 5.2.0 for now.

**Comment by dickulus** [comment]
downgraded too

**Comment by darkmanlv** [comment]
> May I ask how you're hiding it [darkmanlv](https://github.com/darkmanlv)? Thanks

You could always use Virtual Desktop (windows 10, windows 11). Windows Key + Ctrl + D :)

**Comment by Guiguiolive** [comment]
It's in the Changelog for 5.3.3 stable. So it's not a bug.
But what is the point of removing this feature???

**Comment by SteindelSE** [comment]
Downgraded to 5.2 for the foreseeable future. @nicehashdev You guys should really reconsider this change. Caving to the will of a corporation for the sake of very few at the detriment of very many is an objectively poor choice. Your primary user base will happily deal with "false positives" from third party antiviruses, since I'm guessing the majority of them don't use third party antivirus software to begin with...

**Comment by limacohen** [comment]
@Draghmar @DonCaliOni https://github.com/nicehash/NiceHashQuickMiner/issues/697#issuecomment-978493209
But @darkmanlv suggestion works too, I always forget about virtual desktops in Windows.

**Comment by darkmanlv** [comment]
Found another one solution :) Use version NHQM 0.5.2, but update manually excavator.exe to new version from NHQM_v0.5.3.3 =) and disable AutoUpdate in config ("bNoAutoUpdate" : true)

**Comment by darkmanlv** [comment]
https://github.com/AlexDumoJM484

as i said, you can use 0.5.2 but update manually excavator.exe from newest one :) so it will hide and use latest mining software

**Comment by harr2969** [comment]
> Found another solution :) Use version NHQM 0.5.2, but update manually excavator.exe to new version from NHQM_v0.5.3.3 =) and disable AutoUpdate in config ("bNoAutoUpdate" : true)

This worked beautifully. Thank you.

**Comment by DonCaliOni** [comment]
> Found another solution :) Use version NHQM 0.5.2, but update manually excavator.exe to new version from NHQM_v0.5.3.3 =) and disable AutoUpdate in config ("bNoAutoUpdate" : true)

To clarify, do I just replace the new 'excavator.exe' file in the NH QM folder where 0.5.2 is installed? Or do I need to install it somehow?

Thanks

**Comment by Hukuma1** [comment]
That's what I did. Works fine. Only issue is I get the popup to update my QuickMiner on launch. I disabled auto updates, but is there a way to disable it checking for updates as well?

<img width="231" alt="update" src="https://user-images.githubusercontent.com/54511555/153633591-a499d6e9-5963-4bcc-92ff-6a7996884c3c.png">

**Comment by joachimtingvold** [comment]
Excellent example of how to get your users to keep using old, and potentially unsecure, software. Good job, NiceHash!

A +1 from me to give this option back. I also applied the workaround suggested above (downgrade to 0.5.2 and manually upgrade excavator.exe).

**Comment by wanzhiyu** [comment]
Need this feature back too.

**Comment by divdib** [comment]
It is a very important feature, please bring it back!!!

**Comment by GnaXi** [comment]
Whelp. Time to find an alternative to NiceHash, I guess...

**Comment by SteindelSE** [comment]
> Whelp. Time to find an alternative to NiceHash, I guess...

The worst part is this repository doesn't even contain the code. It's just images, optimization profiles, etc. So we're unable to fork it and reimplement the feature for ourselves. Best alternative so far seems to be just to extract the latest exacavtor.exe from new updates and keep overwriting it in a 0.5.2 install. Extremely disappointing.

**Comment by Hukuma1** [comment]
Can we at least hope for Nicehash not to remove our ability to keep using the older exe paired with newer excavator? Or will they go full evil and start requiring checking of versions?

**Comment by SteindelSE** [comment]
> Can we at least hope for Nicehash not to remove our ability to keep using the older exe paired with newer excavator? Or will they go full evil and start requiring checking of versions?

If you were worried about it, why present the idea?

**Comment by Hukuma1** [comment]
They're not dumb. I just want to make sure they're not malicious too.

**Comment by darrencbarnard** [comment]
Downgraded to 5.2 for the foreseeable future. This is an Excellent example of how to get your users to keep using old, and potentially unsecure, software. Great job @nicehashdev

**Comment by gettract** [comment]
+1

**Comment by darkmanlv** [comment]
excavator.exe of 0.5.3.3 started to show low hashrates, update excavator.exe from 0.5.3.6 RC and hashrate will be back :)

**Comment by Dohtar1337** [comment]
Will not implement for now. We want Excavator and QM to be compliant with antivirus requests.

**Comment by Postur** [comment]
> Will not implement for now. We want Excavator and QM to be compliant with antivirus requests.

@Dohtar1337 
Could you elaborate on why you want to conform to these requests, and what the requests even are?

What benefits are there for NiceHash?
What benefits are there for Users?

I have tons of services running on my computer, legitimate services with no gui or anything a user might interact with.

Background processes are an important part of personal computing. as well is user control.

Please help us understand, what reasoning there is for not allowing NHQM to run in the 'background'.

Reasoning is everything, simply stating you won't do it is bad communication, and you will piss off legitimate users.

**Comment by sonicfelipemt** [comment]
> +1 to this request. Just updated to 0.5.3.0 and I can no longer hide Excavator. The entire reason I like NHQM is the fact that I can just use the little tray icon to control it and forget about it while I do other things - having an icon in the task bar means Excavator is now sitting alongside all my actually-intended-to-be-used icons, and just adds another thing to skip over with Alt-Tab.

Same!
DEAR GOD HOW CAN THEY CRACK LHR AND AT THE SAME TIME BREAK UI AND CONFIGS LIKE THIS!

**Comment by sonicfelipemt** [comment]
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by chr0m** [comment]
Damn, I stayed on 5.2 for ages because of this and foolishly updated to 5.3.6 just now and have this ugly console window always open. Looks like I'll be "downgrading" again.

**Comment by DonCaliOni** [comment]
> 

Shut down QuickMiner, edit the nhqm.conf file with the value of "bNoAutoUpdate" : true. Problem solved.

**Comment by Apryed** [comment]
Any way to start a petition and not just wait till they realice "WoW, this will be the next mind blowing option... we are such a genius." ?

Downgrading is not an option...
